"""Quote Composer Agent -- drafts every customer-facing email in the system.

Template-based by default (deterministic, testable, and it is
constitutionally unable to invent a price/product it wasn't given). If
ANTHROPIC_API_KEY is configured, an LLM polish pass rewrites the prose while
the facts block (line items/prices/total/reference) stays computed in Python
and is passed to the model as fixed context -- never generated by it. See
SPEC.md agent #6 and the "guardrails" cross-cutting concern.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

import config
import db
from integrations import llm_client


def _validity_date() -> str:
    return (datetime.now(timezone.utc) + timedelta(days=config.QUOTE_VALIDITY_DAYS)).strftime("%d %b %Y")


def _line_items_block(line_items: list[dict]) -> tuple[str, float]:
    lines = []
    total = 0.0
    for li in line_items:
        qty = li.get("quantity") or 1
        price = li.get("resolved_price") or 0.0
        line_total = qty * price
        total += line_total
        lines.append(
            f"  - {qty} x {li.get('resolved_name')} ({li.get('resolved_sku')}) "
            f"@ {price:,.2f} {li.get('currency', 'USD')} = {line_total:,.2f} {li.get('currency', 'USD')}"
        )
    return "\n".join(lines), total


def _maybe_polish(system: str, draft_text: str) -> str:
    if not llm_client.available():
        return draft_text
    try:
        return llm_client.complete(
            system=system + " Only rewrite tone/phrasing -- do not change any number, SKU, "
                             "product name, date, or the reference token. Return only the email body.",
            user=draft_text,
        )
    except Exception:
        return draft_text  # never let an LLM hiccup block a draft from being produced


def compose_initial_quote(thread: dict, line_items: list[dict], contact: dict | None) -> dict:
    items_block, total = _line_items_block(line_items)
    currency = line_items[0]["currency"] if line_items else "USD"
    name = contact.get("contact_name") if contact else thread.get("customer_name", "there")
    subject = f"Your quote is ready [Ref: {thread['id']}]"
    body = (
        f"Hi {name},\n\n"
        f"Thanks for reaching out. Here's your quote:\n\n"
        f"{items_block}\n\n"
        f"Total: {total:,.2f} {currency}\n"
        f"Valid until: {_validity_date()}\n\n"
        f"To move forward, just reply to this email with one of the following:\n"
        f"  - \"Accept\" to confirm the order\n"
        f"  - \"Reject\" if this isn't a fit\n"
        f"  - Any question you'd like answered before deciding\n\n"
        f"Please keep the reference tag in the subject line when you reply so we can route it "
        f"straight to the right place.\n\n"
        f"Best,\nQuoting Team"
    )
    body = _maybe_polish("You are drafting a friendly, concise B2B sales quote email.", body)
    draft = db.create_draft(thread["id"], kind="quote", subject=subject, body=body,
                             total=total, currency=currency)
    db.log_decision(
        thread["id"], "composer",
        f"Drafted initial quote v{draft['version']}, total {total:,.2f} {currency}",
        {"draft_id": draft["id"], "total": total},
    )
    return draft


def compose_query_response(thread: dict, question_text: str, line_items: list[dict],
                            contact: dict | None) -> dict:
    items_block, total = _line_items_block(line_items)
    currency = line_items[0]["currency"] if line_items else "USD"
    name = contact.get("contact_name") if contact else thread.get("customer_name", "there")
    subject = f"Re: your question about the quote [Ref: {thread['id']}]"
    body = (
        f"Hi {name},\n\n"
        f"Thanks for the question -- here's what we have on file for your quote:\n\n"
        f"{items_block}\n\n"
        f"Total: {total:,.2f} {currency}\n\n"
        f"Regarding what you asked (\"{question_text.strip()[:280]}\"): "
        f"our current quote above reflects the accurate, up-to-date pricing and availability "
        f"for these items. Let us know if you'd like to accept, adjust quantities, or ask "
        f"anything else.\n\n"
        f"Best,\nQuoting Team"
    )
    body = _maybe_polish("You are answering a customer's clarifying question about an existing quote.", body)
    draft = db.create_draft(thread["id"], kind="query_response", subject=subject, body=body,
                             total=total, currency=currency)
    db.log_decision(
        thread["id"], "composer",
        f"Drafted query response v{draft['version']}",
        {"draft_id": draft["id"], "question": question_text[:280]},
    )
    return draft


def compose_rejection_followup(thread: dict, inferred_reason: str, contact: dict | None) -> dict:
    name = contact.get("contact_name") if contact else thread.get("customer_name", "there")
    subject = f"Quick question about the quote [Ref: {thread['id']}]"
    reason_line = {
        "price": "whether the pricing was the sticking point (we may have flexibility depending on volume/term)",
        "availability": "whether availability/lead time was a concern",
        "timeline": "whether the delivery timeline didn't fit your schedule",
    }.get(inferred_reason, "what didn't work about the quote")
    body = (
        f"Hi {name},\n\n"
        f"Thanks for letting us know the quote isn't going ahead. To help us do better next time, "
        f"could you tell us {reason_line}? Any detail helps.\n\n"
        f"If anything changes on your end, we'd be glad to put together a new quote.\n\n"
        f"Best,\nQuoting Team"
    )
    body = _maybe_polish("You are sending a brief, non-pushy 'why didn't this work out' follow-up.", body)
    draft = db.create_draft(thread["id"], kind="rejection_followup", subject=subject, body=body,
                             total=0.0, currency="USD")
    db.log_decision(
        thread["id"], "composer",
        f"Drafted rejection follow-up v{draft['version']}, inferred reason={inferred_reason}",
        {"draft_id": draft["id"], "inferred_reason": inferred_reason},
    )
    return draft


def compose_reminder(thread: dict, stage: str, line_items: list[dict], contact: dict | None) -> dict:
    items_block, total = _line_items_block(line_items)
    currency = line_items[0]["currency"] if line_items else "USD"
    name = contact.get("contact_name") if contact else thread.get("customer_name", "there")
    ordinal = "second " if stage == "2nd" else ""
    subject = f"{'Following up again' if stage == '2nd' else 'Just checking in'} on your quote [Ref: {thread['id']}]"
    body = (
        f"Hi {name},\n\n"
        f"This is a {ordinal}friendly nudge on the quote we sent over:\n\n"
        f"{items_block}\n\n"
        f"Total: {total:,.2f} {currency}\n\n"
        f"Would you like to accept, ask a question, or let us know it's not a fit? "
        f"Happy to help with whatever you need.\n\n"
        f"Best,\nQuoting Team"
    )
    body = _maybe_polish("You are sending a brief, low-pressure reminder email about a pending quote.", body)
    draft = db.create_draft(thread["id"], kind=f"reminder_{stage}", subject=subject, body=body,
                             total=total, currency=currency)
    db.log_decision(
        thread["id"], "composer",
        f"Drafted {stage} reminder v{draft['version']}",
        {"draft_id": draft["id"], "stage": stage},
    )
    return draft
